/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fyquuhzjsihashtvdwlh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5cXV1aHpqc2loYXNodHZkd2xoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzNjM3NzgsImV4cCI6MjA4MTkzOTc3OH0.BbAyQ7HkjJJ0j-sWg4sqqT0dOd_61D5NXfEI-t2iigY"